INSERT INTO uraian_kwitansis (batch_kwitansi_id, nama_uraian, jumlah_uraian, satuan_uraian, keterangan_uraian, created_at, updated_at) VALUES
(1, 'Besi Hollow 4x4', 100, 'batang', 'Besi hollow untuk rangka plafon', NOW(), NOW()),
(1, 'Batu Bata', 200, 'biji', 'Batu bata merah untuk dinding', NOW(), NOW()),
(1, 'Semen', 50, 'sak', 'Semen Portland untuk plester', NOW(), NOW()),
(1, 'Pasir', 500, 'kg', 'Pasir untuk adukan semen', NOW(), NOW()),
(1, 'Besi Beton', 150, 'batang', 'Besi beton untuk pondasi', NOW(), NOW()),
(1, 'Papan Triplek', 10, 'lembar', 'Triplek untuk penutup', NOW(), NOW()),
(1, 'Kawat Baja', 100, 'roll', 'Kawat baja untuk pengikat', NOW(), NOW()),
(1, 'Cat Dinding', 20, 'kaleng', 'Cat untuk finishing dinding', NOW(), NOW()),
(1, 'Atap Spandek', 15, 'lembar', 'Atap spandek untuk pelindung', NOW(), NOW()),
(1, 'Pipa PVC', 50, 'meter', 'Pipa PVC untuk saluran air', NOW(), NOW()),
(1, 'Keramik Lantai', 200, 'lembar', 'Keramik untuk lantai', NOW(), NOW()),
(1, 'Seng', 10, 'lembar', 'Seng untuk atap', NOW(), NOW()),
(1, 'Bahan Aditif', 5, 'kg', 'Aditif untuk semen', NOW(), NOW()),
(1, 'Batu Kali', 300, 'kg', 'Batu kali untuk fondasi', NOW(), NOW()),
(1, 'Papan Kayu', 50, 'lembar', 'Papan kayu untuk konstruksi', NOW(), NOW()),
(1, 'Gergaji', 5, 'buah', 'Gergaji untuk memotong kayu', NOW(), NOW()),
(1, 'Sekrap', 10, 'buah', 'Sekrap untuk penghalusan permukaan', NOW(), NOW()),
(1, 'Kuku Besi', 1000, 'biji', 'Kuku besi untuk menyambung', NOW(), NOW()),
(1, 'Plester', 100, 'kg', 'Plester untuk finishing dinding', NOW(), NOW()),
(1, 'Bahan Waterproofing', 10, 'kg', 'Bahan untuk mencegah kebocoran', NOW(), NOW()),
(1, 'Paku', 500, 'biji', 'Paku untuk penyambungan', NOW(), NOW()),
(1, 'Insulasi Suara', 20, 'lembar', 'Bahan untuk peredam suara', NOW(), NOW()),
(1, 'Kaca', 5, 'lembar', 'Kaca untuk jendela', NOW(), NOW()),
(1, 'Kunci Pintu', 50, 'set', 'Kunci untuk pintu', NOW(), NOW()),
(1, 'Tutup Pipa', 100, 'buah', 'Tutup untuk pipa PVC', NOW(), NOW()),
(1, 'Baja Ringan', 20, 'batang', 'Baja ringan untuk rangka atap', NOW(), NOW()),
(1, 'Alat Pengukur', 10, 'buah', 'Alat untuk pengukuran', NOW(), NOW()),
(1, 'Semprot Cat', 5, 'buah', 'Alat semprot untuk cat', NOW(), NOW()),
(1, 'Sisir Keramik', 10, 'buah', 'Alat untuk keramik', NOW(), NOW()),
(1, 'Obeng', 20, 'buah', 'Obeng untuk perbaikan', NOW(), NOW()),
(1, 'Tali Rafia', 100, 'roll', 'Tali untuk mengikat', NOW(), NOW()),
(1, 'Kain Lap', 50, 'buah', 'Kain untuk membersihkan', NOW(), NOW()),
(1, 'Filter Air', 10, 'buah', 'Filter untuk sistem air', NOW(), NOW()),
(1, 'Kran Air', 20, 'buah', 'Kran untuk saluran air', NOW(), NOW()),
(1, 'Saringan Pasir', 10, 'buah', 'Saringan untuk pasir', NOW(), NOW()),
(1, 'Kabel Listrik', 200, 'meter', 'Kabel untuk instalasi listrik', NOW(), NOW()),
(1, 'Lampu', 50, 'buah', 'Lampu untuk penerangan', NOW(), NOW()),
(1, 'Colokan Listrik', 30, 'buah', 'Colokan untuk instalasi listrik', NOW(), NOW()),
(1, 'Taman Air', 1, 'set', 'Taman air untuk hiasan', NOW(), NOW()),
(1, 'Genset', 1, 'buah', 'Generator set untuk listrik cadangan', NOW(), NOW()),
(1, 'Kursi Lipat', 10, 'buah', 'Kursi untuk keperluan acara', NOW(), NOW()),
(1, 'Meja Lipat', 5, 'buah', 'Meja untuk keperluan acara', NOW(), NOW()),
(1, 'Kamar Mandi Portable', 1, 'buah', 'Kamar mandi untuk keperluan luar', NOW(), NOW()),
(1, 'Tangga', 3, 'buah', 'Tangga untuk akses tinggi', NOW(), NOW()),
(1, 'Wastafel', 5, 'buah', 'Wastafel untuk kamar mandi', NOW(), NOW()),
(1, 'Toilet', 5, 'buah', 'Toilet untuk kebutuhan', NOW(), NOW()),
(1, 'Bak Mandi', 5, 'buah', 'Bak mandi untuk kamar mandi', NOW(), NOW()),
(1, 'Shower', 5, 'buah', 'Shower untuk kamar mandi', NOW(), NOW()),
(1, 'Pipa Air Panas', 20, 'meter', 'Pipa untuk sistem air panas', NOW(), NOW()),
(1, 'Kran Air Panas', 20, 'buah', 'Kran untuk air panas', NOW(), NOW()),
(1, 'Sponge Cat', 50, 'buah', 'Sponge untuk cat', NOW(), NOW()),
(1, 'Kain Pel', 50, 'buah', 'Kain pel untuk membersihkan', NOW(), NOW()),
(1, 'Baskom', 20, 'buah', 'Baskom untuk kebutuhan', NOW(), NOW()),
(1, 'Ember', 20, 'buah', 'Ember untuk kebutuhan', NOW(), NOW()),
(1, 'Pipa Drainase', 100, 'meter', 'Pipa untuk drainase', NOW(), NOW()),
(1, 'Cat Kayu', 10, 'kaleng', 'Cat untuk finishing kayu', NOW(), NOW()),
(1, 'Gergaji Listrik', 2, 'buah', 'Gergaji listrik untuk memotong', NOW(), NOW()),
(1, 'Kunci Inggris', 10, 'buah', 'Kunci inggris untuk perbaikan', NOW(), NOW()),
(1, 'Kunci Pas', 10, 'buah', 'Kunci pas untuk perbaikan', NOW(), NOW()),
(1, 'Palu', 20, 'buah', 'Palu untuk memukul', NOW(), NOW()),
(1, 'Kikir', 10, 'buah', 'Kikir untuk meratakan permukaan', NOW(), NOW()),
(1, 'Kursi', 20, 'buah', 'Kursi untuk kebutuhan', NOW(), NOW()),
(1, 'Meja', 20, 'buah', 'Meja untuk kebutuhan', NOW(), NOW()),
(1, 'Alat Pemotong', 5, 'buah', 'Alat untuk memotong', NOW(), NOW()),
(1, 'Alat Bor', 5, 'buah', 'Alat bor untuk lubang', NOW(), NOW()),
(1, 'Sepatu Safety', 20, 'pasang', 'Sepatu keselamatan untuk pekerja', NOW(), NOW()),
(1, 'Sarung Tangan', 50, 'pasang', 'Sarung tangan untuk perlindungan', NOW(), NOW()),
(1, 'Masker', 100, 'buah', 'Masker untuk perlindungan', NOW(), NOW()),
(1, 'Gergaji Kecil', 5, 'buah', 'Gergaji kecil untuk detail', NOW(), NOW()),
(1, 'Alat Ukur Suhu', 2, 'buah', 'Alat untuk mengukur suhu', NOW(), NOW()),
(1, 'Kabel TV', 50, 'meter', 'Kabel untuk instalasi TV', NOW(), NOW()),
(1, 'Antena TV', 5, 'buah', 'Antena untuk penerimaan sinyal', NOW(), NOW()),
(1, 'Peredam Suara', 10, 'lembar', 'Peredam untuk suara', NOW(), NOW()),
(1, 'Bahan Kimia Pembersih', 5, 'liter', 'Bahan untuk membersihkan', NOW(), NOW()),
(1, 'Tang', 10, 'buah', 'Tang untuk perbaikan', NOW(), NOW()),
(1, 'Palang Pipa', 20, 'buah', 'Palang untuk pipa', NOW(), NOW()),
(1, 'Batu Kerikil', 100, 'kg', 'Kerikil untuk campuran', NOW(), NOW()),
(1, 'Cairan Pembersih', 5, 'liter', 'Cairan untuk membersihkan', NOW(), NOW()),
(1, 'Kain Lembut', 50, 'buah', 'Kain untuk menyeka', NOW(), NOW()),
(1, 'Peralatan Mandi', 20, 'set', 'Peralatan untuk mandi', NOW(), NOW()),
(1, 'Perabot Dapur', 20, 'set', 'Perabot untuk dapur', NOW(), NOW()),
(1, 'Peralatan Kebun', 20, 'set', 'Peralatan untuk berkebun', NOW(), NOW()),
(1, 'Lampu Led', 50, 'buah', 'Lampu hemat energi', NOW(), NOW()),
(1, 'Tinta Printer', 5, 'kaleng', 'Tinta untuk printer', NOW(), NOW()),
(1, 'Kertas Print', 50, 'rim', 'Kertas untuk printer', NOW(), NOW()),
(1, 'Papan Bahan Bakar', 5, 'lembar', 'Papan untuk pembakaran', NOW(), NOW()),
(1, 'Kasa Perak', 100, 'lembar', 'Kasa untuk penyaringan', NOW(), NOW()),
(1, 'Alat Cukur', 5, 'set', 'Alat untuk mencukur', NOW(), NOW()),
(1, 'Palu Kecil', 10, 'buah', 'Palu kecil untuk detail', NOW(), NOW());
