INSERT INTO uraian_kwitansis (batch_kwitansi_id, nama_uraian, jumlah_uraian, satuan_uraian, keterangan_uraian, created_at, updated_at)
VALUES
(1, 'Pemasangan Besi Hollow', 50, 'batang', 'Pemasangan besi hollow untuk plafon', NOW(), NOW()),
(2, 'Penggunaan Semen Portland', 25, 'sack', 'Semen portland untuk pondasi rumah', NOW(), NOW()),
(3, 'Pemasangan Bata Merah', 750, 'buah', 'Bata merah untuk tembok bagian dalam', NOW(), NOW()),
(4, 'Pemasangan Pipa PVC 3 inch', 150, 'batang', 'Instalasi pipa air bersih', NOW(), NOW()),
(5, 'Pemasangan Kabel Listrik', 300, 'meter', 'Instalasi kabel listrik untuk lantai 2', NOW(), NOW()),
(6, 'Pemasangan Besi Beton 12mm', 150, 'batang', 'Besi beton untuk kolom struktur', NOW(), NOW()),
(7, 'Penggunaan Besi Ulir 10mm', 200, 'batang', 'Besi ulir untuk balok pengaman', NOW(), NOW()),
(8, 'Pemasangan Gypsum Board', 100, 'lembar', 'Plafon gypsum untuk ruang tamu', NOW(), NOW()),
(9, 'Penggunaan Triplek 12mm', 80, 'lembar', 'Triplek untuk lantai mezzanine', NOW(), NOW()),
(10, 'Pengecatan Tembok', 40, 'kaleng', 'Pengecatan tembok dengan cat putih', NOW(), NOW()),

(11, 'Pengurugan Pasir Urug', 3000, 'm3', 'Pengurugan tanah untuk lantai dasar', NOW(), NOW()),
(12, 'Pemasangan Kalsiboard 6mm', 120, 'lembar', 'Kalsiboard untuk partisi interior', NOW(), NOW()),
(1, 'Pemasangan Wiremesh M8', 60, 'lembar', 'Wiremesh untuk penguat lantai dak', NOW(), NOW()),
(2, 'Penggunaan GRC Board 4mm', 150, 'lembar', 'GRC untuk partisi ringan', NOW(), NOW()),
(3, 'Pemasangan Keramik Lantai 40x40', 300, 'm2', 'Pemasangan keramik lantai untuk ruang keluarga', NOW(), NOW()),
(4, 'Pemasangan Atap Seng Gelombang', 80, 'lembar', 'Atap seng untuk gudang belakang', NOW(), NOW()),
(5, 'Penggunaan Spandek 0.3mm', 60, 'lembar', 'Spandek untuk kanopi depan', NOW(), NOW()),
(6, 'Pemasangan Paku 10cm', 3000, 'buah', 'Pemasangan paku untuk rangka plafon', NOW(), NOW()),
(7, 'Pemasangan Engsel Pintu', 150, 'pasang', 'Engsel pintu untuk seluruh pintu utama', NOW(), NOW()),
(8, 'Penggunaan Handle Pintu', 80, 'buah', 'Handle pintu untuk ruang tamu', NOW(), NOW()),

(9, 'Pemasangan Pintu Kayu Jati', 30, 'buah', 'Pintu kayu jati untuk pintu utama', NOW(), NOW()),
(10, 'Pemasangan Jendela Aluminium', 60, 'unit', 'Jendela aluminium untuk ruang tidur', NOW(), NOW()),
(11, 'Penggunaan Beton Ready Mix K-225', 100, 'm3', 'Beton untuk lantai basement', NOW(), NOW()),
(12, 'Pemasangan Ubin Granit 60x60', 200, 'm2', 'Ubin granit untuk lantai dapur', NOW(), NOW()),
(1, 'Pemasangan Batu Kali', 1000, 'm3', 'Batu kali untuk pondasi kamar mandi', NOW(), NOW()),
(2, 'Penggunaan Batu Split 2/3', 1500, 'm3', 'Batu split untuk pengecoran lantai', NOW(), NOW()),
(3, 'Penggunaan Pasir Beton', 2000, 'm3', 'Pasir beton untuk dinding luar', NOW(), NOW()),
(4, 'Pemasangan Besi Wiremesh M6', 60, 'lembar', 'Wiremesh untuk lantai mezzanine', NOW(), NOW()),
(5, 'Penggunaan Gipsum Cornice', 100, 'batang', 'Gipsum cornice untuk dekorasi plafon', NOW(), NOW()),

(6, 'Pemasangan Papan MDF 18mm', 75, 'lembar', 'Papan MDF untuk furniture built-in', NOW(), NOW()),
(7, 'Pemasangan Besi Siku 5x5', 150, 'batang', 'Besi siku untuk tangga', NOW(), NOW()),
(8, 'Penggunaan Kawat Beton 6mm', 250, 'kg', 'Kawat beton untuk pengikat besi balok', NOW(), NOW()),
(9, 'Pemasangan Besi Plat 5mm', 60, 'lembar', 'Plat besi untuk jembatan tangga', NOW(), NOW()),
(10, 'Penggunaan Keramik Dinding 25x40', 400, 'm2', 'Keramik dinding untuk kamar mandi', NOW(), NOW()),
(11, 'Pemasangan Cermin 100x50', 60, 'lembar', 'Cermin untuk kamar mandi utama', NOW(), NOW()),
(12, 'Pemasangan Tangga Besi', 20, 'unit', 'Tangga besi untuk akses lantai atas', NOW(), NOW()),
(1, 'Pemasangan Besi Kanal C 7.5', 60, 'batang', 'Besi kanal C untuk rangka atap', NOW(), NOW()),
(2, 'Pemasangan Pintu Aluminium', 40, 'unit', 'Pintu aluminium untuk ruang kerja', NOW(), NOW()),

(3, 'Pemasangan Kabel UTP CAT5E', 500, 'meter', 'Instalasi jaringan internet', NOW(), NOW()),
(4, 'Penggunaan Bata Ringan AAC', 1500, 'buah', 'Bata ringan untuk dinding luar', NOW(), NOW()),
(5, 'Pemasangan Plafon PVC', 125, 'lembar', 'Plafon PVC untuk dapur dan kamar mandi', NOW(), NOW()),
(6, 'Pemasangan Besi Siku 3x3', 200, 'batang', 'Besi siku untuk rangka tangga', NOW(), NOW()),
(7, 'Penggunaan Glassblock 20x20', 200, 'buah', 'Glassblock untuk pencahayaan ruang tamu', NOW(), NOW()),
(8, 'Pemasangan Teralis Besi', 100, 'unit', 'Teralis untuk jendela lantai satu', NOW(), NOW()),
(9, 'Penggunaan Cat Anti Bocor', 50, 'kaleng', 'Cat anti bocor untuk atap dak', NOW(), NOW()),
(10, 'Penggunaan Kawat Duri', 300, 'meter', 'Pemasangan kawat duri untuk pagar', NOW(), NOW()),
(11, 'Penggunaan Sekop Pasir', 30, 'buah', 'Sekop untuk pengurugan tanah', NOW(), NOW()),
(12, 'Penggunaan Cangkul Baja', 40, 'buah', 'Cangkul untuk penggalian tanah pondasi', NOW(), NOW()),

(1, 'Pemasangan Paku Beton', 600, 'buah', 'Pemasangan paku beton untuk kusen', NOW(), NOW()),
(2, 'Penggunaan Kayu Meranti', 150, 'batang', 'Kayu meranti untuk atap lantai atas', NOW(), NOW()),
(3, 'Penggunaan Kayu Kamper', 120, 'batang', 'Kayu kamper untuk kusen pintu', NOW(), NOW()),
(4, 'Penggunaan Lem Kayu Aibon', 60, 'kaleng', 'Lem kayu untuk pintu dan jendela', NOW(), NOW()),
(5, 'Penggunaan Besi Kanal H 150', 40, 'batang', 'Besi kanal H untuk struktur utama', NOW(), NOW()),
(6, 'Penggunaan Kawat Las 2mm', 100, 'kg', 'Kawat las untuk pengelasan tangga besi', NOW(), NOW()),
(7, 'Penggunaan Plat Aluminium 3mm', 75, 'lembar', 'Plat aluminium untuk dekorasi dinding', NOW(), NOW()),
(8, 'Pemasangan Genteng Beton Flat', 1000, 'buah', 'Genteng beton untuk atap rumah', NOW(), NOW()),
(9, 'Pemasangan Asbes Gelombang', 90, 'lembar', 'Asbes gelombang untuk gudang', NOW(), NOW());
